services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build: ./backend
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_DATABASE}
      - PGHOST=${DB_HOST}
      - PGPORT=${DB_PORT}
    command: sh -c "npm install && npm start"
    networks:
      - app-network

  frontend:
    build: ./frontend/Votaciones
    image: frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/Votaciones:/Votaciones
      - /Votaciones/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
